### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by firgk** [Zephyr-Knight/SDUT_AUTObook#1]
2024-10-27
登录失败 {'status': 'fail', 'code': '20', 'message': '手机app已停用,请使用微信小程序"一考即过座位预约"等方式预约', 'data': None}
{'status': 'fail', 'code': '20', 'message': '手机app已停用,请使用微信小程序"一考即过座位预约"等方式预约', 'data': None}
serverJ 服务启动
serverJ 推送状态：{'code': 0, 'message': '', 'data': {'pushid': '181688097', 'readkey': 'SCTuYXKz5FSBwkT', 'error': 'SUCCESS', 'errno': 0}}
bark 服务启动
None
![image](https://github.com/user-attachments/assets/727fa4d9-501c-496e-a118-a10532c2630d)

**Comment by kn1ght233** [comment]
通过网页预约座位是可以用的，代码总体逻辑应该没什么问题，使用代码预约不了可能是有的网址被修改了，重新抓包应该可以获得。如果有时间你可以尝试修改下。我已经毕业工作了，可能没时间更新了。

**Comment by firgk** [comment]
好的ok 谢谢, 等我考完研 有时间我会试试
